# Generated by Django 5.0.4 on 2024-05-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passport', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.CharField(max_length=100)),
                ('insurance_payment', models.FloatField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.clients')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insuranceobject')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.contracts')),
            ],
        ),
    ]
