# Generated by Django 5.0.4 on 2024-05-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancepayments',
            old_name='concept_id',
            new_name='contract_id',
        ),
    ]
