# Generated by Django 5.0.4 on 2024-05-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_rename_concept_id_insurancepayments_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceobject',
            name='description',
            field=models.TextField(),
        ),
    ]
